logging:
  level:
    org.neo4j.ogm: WARN

regions:
  count: 20
  loading.threads: 1

leagues:
  loading.threads: 100
  count: 2360
  minRegionAffiliations: 1
  maxRegionAffiliations: 3
  threads:
    size:
      core: 0
      maxpool: 20
    queue:
      capacity: 20000

teams:
  loading.threads: 20000
  count: 100000
  minLeagueMemberships: 1
  maxLeagueMemberships: 5
  minPlayersPerTeam: 8
  maxPlayersPerTeam: 23
  threads:
    size:
      core: 0
      maxpool: 20
    queue:
      capacity: 20000

persons:
  loading.threads: 20000
  threads:
    size:
      core: 0
      maxpool: 20
    queue:
      capacity: 20000