logging:
  level:
    org.neo4j.ogm: WARN


regions:
  count: 20
  loading.threads: 1
leagues:
  loading.threads: 100
  count: 2360
  minRegionAffiliations: 1
  maxRegionAffiliations: 3
  threads:
    size:
      core: 2
      maxpool: 10
    queue:
      capacity: 200
teams:
  count: 1000
  loading.threads: 200
  minLeagueMemberships: 1
  maxLeagueMemberships: 5
  minPlayersPerTeam: 8
  maxPlayersPerTeam: 23
  threads:
      size:
        core: 5
        maxpool: 20
      queue:
        capacity: 20000

persons:
  loading.threads: 200
  threads:
    size:
      core: 2
      maxpool: 20
    queue:
      capacity: 20000