neo4j:
  driver: org.neo4j.ogm.drivers.http.driver.HttpDriver
  url: http://localhost:7474/
  username: neo4j
  password: blah
  packages:
    - org.dentinger.tutorial.domain

logging:
  level:
    org.neo4j.ogm: WARN

regions:
  count: 24
  loading.threads: 1

leagues:
  loading.threads: 10
  count: 2466
  minRegionAffiliations: 1
  maxRegionAffiliations: 3
  threads:
    size:
      core: 0
      maxpool: 20
    queue:
      capacity: 20000

teams:
  loading.threads: 100
  count: 100000
  minLeagueMemberships: 1
  maxLeagueMemberships: 5
  minPlayersPerTeam: 8
  maxPlayersPerTeam: 23
  minFansPerTeam: 2
  maxFansPerTeam: 4
  threads:
    size:
      core: 0
      maxpool: 20
    queue:
      capacity: 20000

persons:
  loading.threads: 20
  threads:
    size:
      core: 0
      maxpool: 20
    queue:
      capacity: 20000

