regions:
  count: 20
  loading.threads: 1
leagues:
  loading.threads: 10
  count: 2360
  minRegionAffiliations: 1
  maxRegionAffiliations: 3
  threads:
    size:
      core: 2
      maxpool: 10
    queue:
      capacity: 200
teams:
  count: 100000
  loading.threads: 100
  minLeagueMemberships: 1
  maxLeagueMemberships: 5
  minPlayersPerTeam: 8
  maxPlayersPerTeam: 23
  threads:
      size:
        core: 5
        maxpool: 20
      queue:
        capacity: 200

persons:
  loading.threads: 500
  threads:
    size:
      core: 2
      maxpool: 20
    queue:
      capacity: 600