neo4j:
  url: http://localhost:7474/
  username: neo4j
  password: blah
  packages:
    - org.dentinger.tutorial.domain

regions:
  count: 20
leagues:
  loading.threads: 5
  count: 3000
  minRegionAffiliations: 1
  maxRegionAffiliations: 3
teams:
  count: 100000
  minLeagueMemberships: 1
  maxLeagueMemberships: 5
  minPlayersPerTeam: 8
  maxPlayersPerTeam: 12

