neo4j:
  url: http://localhost:7474/
  username: neo4j
  password: blah
  packages:
    - org.dentinger.tutorial.domain

region:
  count: 20
league:
  perRegion:
    count: 150
venues:
  count: 100
  count.maxPerLeague: 20

team:
  perLeague:
    count: 400

